# Practical No. 1

## Title
Exploring Deep Learning Libraries and Performing Basic Tensor Operations Using TensorFlow

## Aim
To familiarize students with popular deep learning libraries and perform basic tensor creation and mathematical operations using TensorFlow.

## Scope
This practical introduces the deep learning software ecosystem and covers the installation of TensorFlow, creation of tensors, basic tensor operations, and comparison of commonly used deep learning libraries.

## Dataset
Not Applicable

## Libraries Required
- TensorFlow
- NumPy

## Part A – Installation

### 1. Install TensorFlow using pip

Run the following command in the terminal / command prompt to install TensorFlow:

```bash
pip install tensorflow
```

### 2. Verify the TensorFlow Installation

In [ ]:
# ==========================================================
# Verify that TensorFlow is installed and can be imported
# ==========================================================
try:
    import tensorflow as tf
    print("TensorFlow is installed and working successfully.")
except ImportError:
    print("TensorFlow is NOT installed.")

### 3. Display the Installed TensorFlow Version

In [ ]:
# ==========================================================
# Display the installed TensorFlow version
# ==========================================================
import tensorflow as tf

print("TensorFlow Version:", tf.__version__)

## Part B – Tensor Creation

### 4. Create a Scalar Tensor

In [1]:
import tensorflow as tf

# ==========================================================
# Task: Create a Scalar Tensor (0-D Tensor)
# ==========================================================
# tf.constant() creates an immutable (unchangeable) tensor.
# A scalar contains only a single value and has no dimensions.
scalar = tf.constant(10)

print("Scalar Tensor:")
print(scalar)

Scalar Tensor:
tf.Tensor(10, shape=(), dtype=int32)


### 5. Create a Vector Tensor

In [2]:
# ==========================================================
# Task: Create a Vector Tensor (1-D Tensor)
# ==========================================================
# A vector is a one-dimensional collection of values.
# Here, the vector contains four elements.

vector = tf.constant([10, 20, 30, 40])

print("Vector Tensor:")
print(vector)

Vector Tensor:
tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)


### 6. Create a Matrix Tensor

In [3]:
# ==========================================================
# Task: Create a Matrix Tensor (2-D Tensor)
# ==========================================================
# A matrix consists of rows and columns.
# This matrix has:
# 2 rows
# 3 columns

matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix Tensor:")
print(matrix)

Matrix Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


### 7. Create a Three-Dimensional Tensor

In [4]:
# ==========================================================
# Task: Create a Three-Dimensional Tensor (3-D Tensor)
# ==========================================================
# A 3-D tensor can be thought of as multiple matrices stacked together.
#
# Structure:
# Layer 1
# [[1,2],
#  [3,4]]
# Layer 2
# [[5,6],
#  [7,8]]
# Total shape = (2,2,2)
# First 2  -> Number of matrices (layers)
# Second 2 -> Rows in each matrix
# Third 2  -> Columns in each matrix

tensor_3d = tf.constant([
    [
        [1, 2],
        [3, 4] ],
    [
        [5, 6],
        [7, 8] ]
])

print("Three-Dimensional Tensor:")
print(tensor_3d)

Three-Dimensional Tensor:
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


## Part C – Tensor Operations

### 8. Perform Tensor Addition

In [5]:
# ==========================================================
# Task – Tensor Addition
# ==========================================================

# Create two tensors of the same shape
tensor1 = tf.constant([[1, 2],[3, 4]])

tensor2 = tf.constant([[5, 6],[7, 8]])

# tf.add() performs element-wise addition.
# Each element in tensor1 is added to the corresponding
# element in tensor2.

addition = tf.add(tensor1, tensor2)

# Display the result
print("Tensor Addition:")
print(addition)

Tensor Addition:
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


### 9. Perform Tensor Subtraction

In [6]:
# ==========================================================
# Task – Tensor Subtraction
# ==========================================================

# Create two tensors of the same shape
tensor1 = tf.constant([[1, 2], [3, 4]])

tensor2 = tf.constant([[5, 6],[7, 8]])

# tf.subtract() performs element-wise subtraction.
# Each element in tensor2 is subtracted from the
# corresponding element in tensor1.

subtraction = tf.subtract(tensor1, tensor2)

# Display the result
print("Tensor Subtraction:")
print(subtraction)

Tensor Subtraction:
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


### 10. Perform Tensor Multiplication (Element-wise)

Note: Element-wise multiplication (`tf.multiply`) is different from matrix multiplication (`tf.matmul`), which is shown in the next task.

In [7]:
# ==========================================================
# Task – Tensor Multiplication (Element-wise)
# ==========================================================

# Create two tensors of the same shape
tensor1 = tf.constant([[1, 2],
                       [3, 4]])

tensor2 = tf.constant([[5, 6],
                       [7, 8]])

# tf.multiply() performs element-wise multiplication.
# Each element in tensor1 is multiplied by the
# corresponding element in tensor2.

multiplication = tf.multiply(tensor1, tensor2)

# Display the result
print("Tensor Multiplication:")
print(multiplication)

Tensor Multiplication:
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


### 11. Perform Matrix Multiplication

This uses proper matrix multiplication rules (Row x Column), not element-wise multiplication.

In [8]:
# ==========================================================
# Task – Matrix Multiplication
# ==========================================================

# Create two matrices (2 x 2)
matrix1 = tf.constant([[1, 2],[3, 4]])

matrix2 = tf.constant([[5, 6],[7, 8]])

# tf.matmul() performs matrix multiplication.
# Unlike tf.multiply(), it follows the rules of
# matrix multiplication (Row x Column).

matrix_multiplication = tf.matmul(matrix1, matrix2)

# Display the result
print("Matrix Multiplication:")
print(matrix_multiplication)

Matrix Multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### 12. Reshape an Existing Tensor

In [9]:
# ==========================================================
# Task – Reshape an Existing Tensor
# ==========================================================

# Create a tensor of shape (2 x 2)
tensor = tf.constant([[1, 2],[3, 4]])

# Display the original tensor
print("Original Tensor:")
print(tensor)

# tf.reshape() changes the shape of a tensor
# without changing its data.
# Here, the tensor is reshaped from (2, 2) to (4, 1).

reshaped_tensor = tf.reshape(tensor, (4, 1))

# Display the reshaped tensor
print("\nReshaped Tensor:")
print(reshaped_tensor)

Original Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Reshaped Tensor:
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)


### 13. Convert a NumPy Array into a TensorFlow Tensor

In [10]:
# ==========================================================
# Task – Convert a NumPy Array into a TensorFlow Tensor
# ==========================================================

# Import the required library
import numpy as np

# Create a NumPy array
numpy_array = np.array([[10, 20],[30, 40]])

# Display the NumPy array
print("NumPy Array:")
print(numpy_array)

# tf.convert_to_tensor() converts the NumPy array
# into a TensorFlow tensor.

tensorflow_tensor = tf.convert_to_tensor(numpy_array)

# Display the TensorFlow tensor
print("\nTensorFlow Tensor:")
print(tensorflow_tensor)

NumPy Array:
[[10 20]
 [30 40]]

TensorFlow Tensor:
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int64)


## Part D – Framework Comparison

### 14. Study TensorFlow, PyTorch, and Keras

| Feature | TensorFlow | PyTorch | Keras |
|---|---|---|---|
| Developed/Backed By | Google | Meta (Facebook) | Originally independent; now integrated with TensorFlow |
| Main Strength | Production deployment & scalability | Flexibility & dynamic computation graphs | Simplicity & ease of building models |
| Ease of Use | Moderate | Moderate to Easy | Very Easy |
| Typical Applications | Large-scale production systems, mobile/embedded deployment | Research, rapid prototyping | Quick prototyping, teaching, beginner-friendly projects |
| Advantages | Strong deployment tools, large community, cross-platform support | Pythonic syntax, easy debugging, strong research adoption | High-level, readable API, fast model building, runs on top of TensorFlow |